<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>AL System</title>
    </head>
    <body>
        <h1>Ocorreu um erro</h1>
        <h2><?php echo $this->message ?></h2>
        <?php if (isset($this->exception)): ?>
            <h3>Informação da exceção:</h3>
            <p>
                <b>Mensagem:</b> <?php echo $this->exception->getMessage() ?>
            </p>
            <h3>Rastreamento da pilha:</h3>
            <pre><?php echo $this->exception->getTraceAsString() ?></pre>
            <h3>Parâmetros da requisição:</h3>
            <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
        <?php endif ?>
    </body>
</html>